matchID-project/deces-ui

public/index.html
src/App.svelte
src/components/tools/search.js

- add google analytics (like in react version)
- fix double api call on load

Ga and 2x api bug

---

public/index.html
src/components/tools/GoogleAnalytics.svelte
src/components/views/SearchBox.svelte

to be tried on 'dev' branch and dev-deces.matchid.io

Ga svelete component

---

src/components/views/MatchIDHeader.svelte

Remove Serch UI reference
Add www prefix to matchid project page

Add www prefix to matchid project page

---

Makefile
src/App.svelte
src/components/tools/stores.js
src/components/views/MatchIDHeader.svelte
src/components/views/Results.svelte
src/components/views/ResultsHeader.svelte

- disable social links as no real traffic provider
- enable ads in feed, for testing

Ads and social

---

src/components/tools/search.js
src/components/tools/stores.js
src/components/views/Autocomplete.svelte
src/components/views/FontAwesomeIcon.svelte
src/components/views/Result.svelte
src/components/views/Results.svelte
src/components/views/ResultsHeader.svelte
src/components/views/SearchBox.svelte

Direct autocomplete

---

src/components/tools/stores.js

query and fuzzy keys already exist
This is why I like TS :)

🥅 Remove duplicated fields in store variable

---

.gitignore
Makefile
docker-compose-dev.yml
nginx/default-dev.template
nginx/run.sh

Call backend with:
backend-config : git clone du repo backend
backend-dev: appel au make du repo du backend (lancement du docker backend développement)
Un test peut être fait sur la route `/api/v0/healthcheck` sur le même port de nginx
attention au changement du template nginx dev qui va pas démarrer si backend n'est pas up

Prepare connection with backend

---

.travis.yml
Makefile
src/App.svelte

Switch api key and docker push after test

---

Makefile
nginx/default-dev.template
nginx/default-run.template

Deploy backend

---

.gitignore
Makefile

use now master branch to deploy

Backend master

---

src/components/views/Place.svelte
src/components/views/Result.svelte

ajout : 
- âge (calculé)
- code INSEE (suite à demande utilisateur)

Code insee

---

src/components/tools/buildResults.js
src/components/tools/runRequest.js
src/components/tools/search.js
src/components/views/Place.svelte
src/components/views/Result.svelte

as specified here : https://github.com/matchID-project/deces-backend/issues/11

New stable api

---

package.json
src/components/tools/buildRequest.js
src/components/tools/runRequest.js
src/components/tools/stores.js
src/components/views/Download.svelte
src/components/views/Pagination.svelte
src/components/views/ResultsHeader.svelte

Add csv download

---

src/components/tools/stores.js
src/components/views/Link.svelte
src/components/views/LinkCheck.svelte
src/components/views/LinkCheckTable.svelte
src/components/views/LinkJob.svelte

better handling of check table : 
- sort by score
- add a regex input for easy filtering each table

Feat record linkage

---

package.json
src/components/tools/stores.js
src/components/tools/useLocalStorage.js
src/components/views/Link.svelte
src/components/views/LinkCheck.svelte
src/components/views/LinkCheckTable.svelte
src/components/views/LinkFile.svelte
src/components/views/LinkJob.svelte
src/components/views/LinkSampleTable.svelte
src/components/views/LinkStep.svelte

Fix large dataset annotation : 
- use indexdb for cache of large results
- separate annotation to other variable for faster sync still using localstorage until ~ 100k lines

Use idb keyval

---

Makefile

while analyzing "simple search" problem

temp dataprep workaround

---

src/components/views/LinkCheck.svelte

Function imported from vanilla js toolkit.

🚸 Replace flat function to maintain support for firefox 52

---

public/css/global.css
src/components/views/LinkCheck.svelte
src/components/views/LinkCheckTable.svelte
src/components/views/LinkField.svelte

- debug mass validation
- improved UI: show similar row on hover

UI link check table

---

src/components/tools/radar.js
src/components/views/Aggregations.svelte
src/components/views/Radar.svelte

Add radar plot to visualize seasonality.

🔘 Radar plot to represent death months

---

public/css/global.css
src/App.svelte
src/components/tools/icons.js
src/components/tools/stores.js
src/components/views/ResultCard.svelte

Adds a dummy screen to enable editing of a record : 
- adds a button to enable edit
- enable editing each record on hover / fields are modified as formatted values
- chose to add a file ou url as a proof for the edit
- if url, fetch to validate the url
Feature (no API call) can be enabled using ctrl+alt+a - a is for "alpha" feature.

Edit records (mock up)

---

nginx/default-dev.template
nginx/default-run.template

Just a small patch to be able to check job status routes using nginx

🚚 Expose job status route in nginx config

---

src/components/views/Info.svelte

Erreur ligne 213 :                  la mairie (ou le consultat) de décès est habilité**e** à transmettre

Correction d'erreurs de syntaxe et de grammaire

---

src/components/views/LinkJobs.svelte

On peut cliquer sur "arrêter ❌" pour arrêter le job

✨ Ajouter un bouton pour supprimer un job qui tourne sur l'interface admin

---

.gitlab-ci.yml
.gitlab/before_build.sh

ça va permettre de faire tourner un workflow dans un gitlab privé de l'administration

🤖 Gitlab workflow

---

src/components/views/Radar.svelte

Fix #582 
Je pense qu'il reste un problème au niveau de l'async, peut être au niveau du callback pour le post processing des données (data callback), mais c'est peu visible.

🐛 Catch error when month and year is not parsed in radar plot

---

src/components/views/LinkCheck.svelte

🎨 Rajouter 'matched' ou 'complete' au fichier généré dans la page link

---

src/components/views/LinkJobs.svelte

Related with https://github.com/matchID-project/deces-backend/issues/252

💥 Don't use random id in job list

---

package-lock.json
package.json
rollup.config.js

J'ai trouvé l'erreur suivant au moment de faire le build du html. 
```
[!] Error: Unexpected token (Note that you need @rollup/plugin-json to import 
JSON files)
node_modules/axios/package.json (2:8)
1: {
2:   "name": "axios",
^
3:   "version": "0.21.4",
4:   "description": "Promise based HTTP client for the browser and node.js",
Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
at error (/deces-ui/node_modules/rollup/dist/shared/rollup.js:151:30)
at Module.error (/deces-ui/node_modules/rollup/dist/shared/rollup.js:10059:16)
at Module.tryParse (/deces-ui/node_modules/rollup/dist/shared/rollup.js:10462:25)
at Module.setSource (/deces-ui/node_modules/rollup/dist/shared/rollup.js:10365:24)
at ModuleLoader.addModuleSource …
```

🐛 Add rollup/plugin-json to build svelte html

---

src/components/views/Download.svelte

🐛 Add fuzzy parameter to download csv request

---

package.json

Fix communes
Adde search from geopoint

Upgrade from deces-backend

---

src/components/views/GedcomTree.svelte
src/components/views/LinkSampleTable.svelte

Prendre en charge des fichier avec des noms en forme de liste:
```
0 @I3@ INDI
1 NAME Maria Antonietta /Torriani/
1 NAME Marchesa Colombi
1 NAME Amelia Lorit
1 NAME La Moda
```
Les fichiers ged ont pas mal de subtilités.

🎨 Handle array names in ged files

---

src/components/views/Info.svelte

Removes rgpd
Adds soutenez-nous

Change info when not found

---

src/components/views/Login.svelte

This modification works with https://github.com/matchID-project/deces-backend/pull/364

✨ Add message when email address is disposable

---

src/components/tools/icons.js
src/components/views/SearchBox.svelte

Add button to clear all text fields

✨ Add clear research inputs button

---

.github/workflows/push.yml
nginx/default-dev.template
nginx/default-run.template

- webhooks
- disposable mails (npo2 etc)
- token renewal fix

Webhook etc.
